version: 2
updates:
  - package-ecosystem: docker
    directory: /.container
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.container/minimal_build
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /apps/dilemma
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /camel/benchmarks/mock_website
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /camel/interpreters/docker
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /camel/toolkits/hybrid_browser_toolkit/ts
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/runtimes/ubuntu_docker_runtime
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/airbnb_mcp
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/chat_with_github
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/chat_with_youtube
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/cloudfare_mcp_camel
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/codeforces_question_solver
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/mistral_OCR
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/multi_agent_research_assistant
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/pptx_toolkit_usecase
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/usecases/youtube_ocr
    schedule:
      interval: daily
