name: Test Minimal Dependency

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "camel/**"
      - "examples/**"
      - "test/integration_test/**"
      - ".github/workflows/test_minimal_dependency.yml"

permissions:
  contents: read

jobs:
  minimal-dependency:
    name: Minimal dependency check
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .

      - name: Run integration test on minimal examples
        env:
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        run: |
          source .venv/bin/activate
          pip install pytest dotenv
          pytest test/integration_test/test_minimal_dependency.py
